<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Products extends Seeder
{
    public function run()
    {
        $data = [
            [
                'category' => 'MIFI Indonesia',
                'country' => 'INDONESIA',
                'packageType' => 'DAILY',
                'dataUsage' => 'FUP 8 GB',
                'deposit' => 500000,
                'dailyPrice' => 40000,
                'stock' => 5,
                'minimumRentDays' => 3,
                'maxDownloadSpeed' => 35.00,
                'maxUploadSpeed' => 15.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/Indonesia.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'Y',
            ],
            [
                'category' => 'MIFI Indonesia',
                'country' => 'INDONESIA',
                'packageType' => 'DAILY',
                'dataUsage' => 'UNLIMITED',
                'deposit' => 500000,
                'dailyPrice' => 60000,
                'stock' => 5,
                'minimumRentDays' => 5,
                'maxDownloadSpeed' => 30.00,
                'maxUploadSpeed' => 15.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Indosat',
                'countryFlagUrl' => '/assets/images/flags/Indonesia.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'MIFI Indonesia',
                'country' => 'INDONESIA',
                'packageType' => 'WEEKLY',
                'dataUsage' => 'FUP 56 GB',
                'deposit' => 500000,
                'dailyPrice' => 28000,
                'stock' => 2,
                'minimumRentDays' => 7,
                'maxDownloadSpeed' => 30.00,
                'maxUploadSpeed' => 10.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/Indonesia.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'MIFI Indonesia',
                'country' => 'INDONESIA',
                'packageType' => 'WEEKLY',
                'dataUsage' => 'FUP 35 GB',
                'deposit' => 500000,
                'dailyPrice' => 25000,
                'stock' => 5,
                'minimumRentDays' => 7,
                'maxDownloadSpeed' => 35.00,
                'maxUploadSpeed' => 15.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Telkomsel',
                'countryFlagUrl' => '/assets/images/flags/Indonesia.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'Y',
            ],
            [
                'category' => 'MIFI Indonesia',
                'country' => 'INDONESIA',
                'packageType' => 'MONTHLY',
                'dataUsage' => 'FUP 100 GB',
                'deposit' => 500000,
                'dailyPrice' => 70000,
                'stock' => 0,
                'minimumRentDays' => 30,
                'maxDownloadSpeed' => 50.00,
                'maxUploadSpeed' => 20.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/Indonesia.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'MIFI International',
                'country' => 'JAPAN',
                'packageType' => 'DAILY',
                'dataUsage' => '5G UNLIMITED',
                'deposit' => 500000,
                'dailyPrice' => 80000,
                'stock' => 5,
                'minimumRentDays' => 2,
                'maxDownloadSpeed' => 50.00,
                'maxUploadSpeed' => 50.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/Japan.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'Y',
            ],
            [
                'category' => 'MIFI International',
                'country' => 'SOUTH KOREA',
                'packageType' => 'WEEKLY',
                'dataUsage' => 'UNLIMITED',
                'deposit' => 500000,
                'dailyPrice' => 70000,
                'stock' => 5,
                'minimumRentDays' => 7,
                'maxDownloadSpeed' => 40.00,
                'maxUploadSpeed' => 40.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/South-Korea.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'MIFI International',
                'country' => 'USA',
                'packageType' => 'WEEKLY',
                'dataUsage' => 'FUP 200 GB',
                'deposit' => 500000,
                'dailyPrice' => 75000,
                'stock' => 0,
                'minimumRentDays' => 7,
                'maxDownloadSpeed' => 50.00,
                'maxUploadSpeed' => 50.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/USA.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'Y',
            ],
            [
                'category' => 'MIFI International',
                'country' => 'US & CANADA',
                'packageType' => 'MONTHLY',
                'dataUsage' => 'UNLIMITED',
                'deposit' => 500000,
                'dailyPrice' => 96000,
                'stock' => 2,
                'minimumRentDays' => 30,
                'maxDownloadSpeed' => 45.00,
                'maxUploadSpeed' => 30.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/US-Canada.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'MIFI International',
                'country' => 'BRAZIL',
                'packageType' => 'MONTHLY',
                'dataUsage' => '4G UNLIMITED',
                'deposit' => 500000,
                'dailyPrice' => 65000,
                'stock' => 5,
                'minimumRentDays' => 30,
                'maxDownloadSpeed' => 30.00,
                'maxUploadSpeed' => 30.00,
                'batteryHours' => 12,
                'sharedDevices' => 8,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/Brazil.jpg',
                'imageUrl' => '/assets/images/mifi.png',
                'notes' => '<ul><li>Wifi can be shared up to 8 users.</li><li>12-14 hours battery life.</li><li>Range of share wifi up to 10 meters.</li><li>Prices do not include shipping and return costs.</li><li>Required deposit IDR 500,000/modem.</li><li>Deposit is only paid once at the beginning of the reservation.</li><li>The wifi package is included with a wifi pouch, adapter & USB charger.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'SIM',
                'country' => 'INDONESIA',
                'packageType' => 'DAILY',
                'dataUsage' => 'FUP 20 GB',
                'deposit' => 0,
                'dailyPrice' => 20000,
                'stock' => 5,
                'minimumRentDays' => 1,
                'maxDownloadSpeed' => 25.00,
                'maxUploadSpeed' => 25.00,
                'batteryHours' => 0,
                'sharedDevices' => 1,
                'network' => 'Indosat',
                'countryFlagUrl' => '/assets/images/flags/Indonesia.jpg',
                'imageUrl' => '/assets/images/sim.png',
                'notes' => '<ul><li>Prices do not include shipping and return costs.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'SIM',
                'country' => 'INDONESIA',
                'packageType' => 'WEEKLY',
                'dataUsage' => 'UNLIMITED',
                'deposit' => 0,
                'dailyPrice' => 30000,
                'stock' => 5,
                'minimumRentDays' => 7,
                'maxDownloadSpeed' => 25.00,
                'maxUploadSpeed' => 25.00,
                'batteryHours' => 0,
                'sharedDevices' => 1,
                'network' => 'Telkomsel',
                'countryFlagUrl' => '/assets/images/flags/Indonesia.jpg',
                'imageUrl' => '/assets/images/sim.png',
                'notes' => '<ul><li>Prices do not include shipping and return costs.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'Y',
            ],
            [
                'category' => 'SIM',
                'country' => 'CHINA',
                'packageType' => 'WEEKLY',
                'dataUsage' => 'FUP 45 GB',
                'deposit' => 0,
                'dailyPrice' => 35000,
                'stock' => 2,
                'minimumRentDays' => 7,
                'maxDownloadSpeed' => 40.00,
                'maxUploadSpeed' => 40.00,
                'batteryHours' => 0,
                'sharedDevices' => 1,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/China.jpg',
                'imageUrl' => '/assets/images/sim.png',
                'notes' => '<ul><li>Prices do not include shipping and return costs.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'SIM',
                'country' => 'QATAR',
                'packageType' => 'WEEKLY',
                'dataUsage' => 'FUP 30 GB',
                'deposit' => 0,
                'dailyPrice' => 25000,
                'stock' => 0,
                'minimumRentDays' => 7,
                'maxDownloadSpeed' => 25.00,
                'maxUploadSpeed' => 25.00,
                'batteryHours' => 0,
                'sharedDevices' => 1,
                'network' => 'Multi-operator',
                'countryFlagUrl' => '/assets/images/flags/Qatar.jpg',
                'imageUrl' => '/assets/images/sim.png',
                'notes' => '<ul><li>Prices do not include shipping and return costs.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'N',
            ],
            [
                'category' => 'SIM',
                'country' => 'SAUDIA ARABIA',
                'packageType' => 'MONTHLY',
                'dataUsage' => 'UNLIMITED',
                'deposit' => 0,
                'dailyPrice' => 20000,
                'stock' => 5,
                'minimumRentDays' => 30,
                'maxDownloadSpeed' => 45.00,
                'maxUploadSpeed' => 45.00,
                'batteryHours' => 0,
                'sharedDevices' => 1,
                'network' => 'STC',
                'countryFlagUrl' => '/assets/images/flags/Saudia-Arabia.jpg',
                'imageUrl' => '/assets/images/sim.png',
                'notes' => '<ul><li>Prices do not include shipping and return costs.</li><li>The extension of the rental period is enough to pay the rental price of the selected package.</li><li>Can be used for all devices.</li></ul>',
                'bestSeller' => 'Y',
            ],
        ];

        $this->db->table('products')->insertBatch($data);
    }
}
